#!/bin/bash -x
#
# This simple script builds the the application for Windows
# using a cross compiler.
#
set -e
make clean
rm -rf qdigi.zip
rm -rf qdigi.exe
rm -rf qdigi
rm -f qdigi
mkdir  qdigi
# Build the image
docker build -t qtdyn .

## in den Container gehen:
####  docker run -it qt bash

# Now extract the generated binary
docker run qtdyn cat qdigi.zip > qdigi.zip
