#!/bin/bash -x
#
# This simple script builds the the application for Windows
# using a cross compiler.
#

# Build the image
docker build -t qt .

## in den Container gehen:
####  docker run -it qt bash

# Now extract the generated binary
####  docker run qt cat release/newDigi.exe >newDigi.exe
