#!/bin/bash -x
#
# This simple script builds the the application for Windows
# using a cross compiler.
#
make clean
rm -rf qdigi.zip
rm -rf qdigi.exe
# Build the image
set -e
docker build -t qtdyn .

## in den Container gehen:
####  docker run -it qt bash

# Now extract the generated binary
docker run qtdyn cat qdigi.zip > qdigi.zip
bash -c "cd ../ && zip qdigi/qdigi.zip qdigi/modules/*.lua"
